on: 
  push:
    branches:
      - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.FTP_USER }}
            server: 193.44.147.188
            port: 21
            local_path: /
            remote_path: /public_html/
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
